# -*- coding: utf-8 -*-
"""textodesafio_google_colab.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bCUh7Jl-n5uOm_d0WeeBrCVSncaRuhYK
"""

!pip install

# Script desenvolvido no Google Colab com Python.

# Importar a biblioteca pandas.
# Importar a biblioteca json.
import pandas as pd
import json

# Leitura do arquivo json com o pandas. No caso do Google Colab, importamos o arquivo para o ambiente, logo, não temos um caminho de repositório.
df = pd.read_json('textodesafio.txt')

# Convertendo o arquivo nativo texto para json.
df_json = df.to_json()

# Carregamento do arquivo json para a variável results e transformar a lista em um dicionário.
json_results = json.loads(df_json)

# Impressão do resultado com o dumps, que converte um objeto python em uma string json.
print(json.dumps(json_results, indent = True))